name: Basic Maintenance

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Installing all dependencies...
        run: npm ci

      - name: Linting...
        run: npm run lint

      - name: Building...
        run: npm run build
